config/routes.rb
Blog::Application.routes.draw do
  resources :profiles

  get "home/index"
  devise_for :blog_users
  resources :comments

  resources :entries

  resources :weblogs

  root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :entry
	#belongs_to :blog_user
	belongs_to :profile

	validates :entry_id, numericality: true
	#validates :user_id, numericality: true
	validates :comment, presence: true,  exclusion: { :in => ["fuck", "禁止ワード"] }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_blog_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @will_comment_entry_id = params[:will_comment_entry_id]
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    logger.debug("^^^^^^^^^^^#{@comment.inspect}")

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.entry, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:entry_id, :comment, :user_id, :profile_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display:none;">
    <%= f.label :entry_id %><br>
    <%= f.number_field :entry_id, value: @will_comment_entry_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, :size=>"160x20" %>
  </div>
  <div class="field" style="display:none;">
    <%= f.label :profile_id %><br>
    <%= f.number_field :profile_id, value: session[:login] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Entry</th>
      <th>Comment</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.entry_id %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to '記事一覧へ', entries_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<!--
<p>
  <strong>Entry:</strong>
  < @comment.entry_id %>
</p>
-->

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<!--
<p>
  <strong>User:</strong>
  < @comment.user_id %>
</p>
-->

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to '記事一覧へ', entries_path %>