config/routes.rb
Blog::Application.routes.draw do
  resources :profiles

  get "home/index"
  devise_for :blog_users
  resources :comments

  resources :entries

  resources :weblogs

  root 'home#index'

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :weblog
	has_many :comments

	validates :weblog_id, numericality: true
	validates :title, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_blog_user!

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    
    @entry_pfofile = Profile.find(@entry.weblog.profile_id)
    logger.debug("----------#{@entry_pfofile}")
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:weblog_id, :title, :body)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display:none;">
    <%= f.label :weblog_id %><br>
    <%= f.number_field :weblog_id, value: Weblog.where(user_id: session[:login]).first.id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    本文には、HTMLタグが使えます。<br>
    <%= f.text_area :body, :size=>"160x20" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table class="table">
  <thead>
    <tr>
      <th>Weblog</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.weblog.blog_name %></td>
        <td><%= entry.title %></td>
        <td><%= link_to 'Show', entry %></td>
        <% if entry.weblog.user_id == session[:login] %>
          <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
          <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>
  
<div style="float:right;">
  <h2>プロフィール</h2>
  <p>
    <strong>Name:</strong>
    <%= @entry_pfofile.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @entry_pfofile.age %>
  </p>

  <p>
    <strong>Hobby:</strong>
    <%= @entry_pfofile.hobby %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= @entry_pfofile.detail %>
  </p>
</div>

<div style="text-align:center;">
<h1 style="margin-top:40px;"><%= @entry.title %></h1>
<p style="margin-top:60px;">
  <hr>
  <%= simple_format(markdown(@entry.body)) %> 
</p>

<p style="margin-top:60px;"> 
  <h2>コメント</h2>
  <% @entry.comments.each do |comment| %>
	  <p>＞　<%= comment.comment %></p>
  <% end %>
</p>

<p style="margin-top:40px;">
<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>
<%= link_to 'コメントする', new_comment_path(will_comment_entry_id: @entry.id) %>
</p>

<p>
  <% if @entry.id != 1 %>
    <%= link_to '前の記事', Entry.find(@entry.id - 1) %>
  <% end %>
  <% if @entry != Entry.last %>
    <%= link_to '次の記事', Entry.find(@entry.id + 1) %>
  <% end %>
</p>
</div>