config/routes.rb
Blog::Application.routes.draw do
  resources :profiles

  get "home/index"
  devise_for :blog_users
  resources :comments

  resources :entries

  resources :weblogs

  root 'home#index'

  

end

app/models/weblog.rb
class Weblog < ActiveRecord::Base
	#belongs_to :blog_user
	belongs_to :profile
	has_many :entries

	validates :profile_id, uniqueness: true, numericality: true
	validates :user_id, uniqueness: true, numericality: true
end

app/controllers/weblogs_controller.rb
class WeblogsController < ApplicationController
  before_action :set_weblog, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_blog_user!

  # GET /weblogs
  # GET /weblogs.json
  def index
    @weblogs = Weblog.all
  end

  # GET /weblogs/1
  # GET /weblogs/1.json
  def show
  end

  # GET /weblogs/new
  def new
    @weblog = Weblog.new
    @weblog_relation_profile = Profile.find(session[:login])
  end

  # GET /weblogs/1/edit
  def edit
    @weblog_relation_profile = Profile.find(session[:login])
  end

  # POST /weblogs
  # POST /weblogs.json
  def create
    @weblog = Weblog.new(weblog_params)

    respond_to do |format|
      if @weblog.save
        format.html { redirect_to @weblog, notice: 'Weblog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weblog }
      else
        format.html { render action: 'new' }
        format.json { render json: @weblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weblogs/1
  # PATCH/PUT /weblogs/1.json
  def update
    respond_to do |format|
      if @weblog.update(weblog_params)
        format.html { redirect_to @weblog, notice: 'Weblog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weblogs/1
  # DELETE /weblogs/1.json
  def destroy
    @weblog.destroy
    respond_to do |format|
      format.html { redirect_to weblogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weblog
      @weblog = Weblog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weblog_params
      params.require(:weblog).permit(:user_id, :blog_name, :profile_id)
    end
end

app/helpers/weblogs_helper.rb
module WeblogsHelper
end

app/views/weblogs/_form.html.erb
<%= form_for(@weblog) do |f| %>
  <% if @weblog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weblog.errors.count, "error") %> prohibited this weblog from being saved:</h2>

      <ul>
      <% @weblog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display:none;">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value:session[:login]  %>
  </div>

  <div class="field" style="display:none;">
    <%= f.label :profile_id %><br>
    <%= f.number_field :profile_id, value:@weblog_relation_profile.id  %>
  </div>

  <div class="field">
    <%= f.label :blog_name %><br>
    <%= f.text_field :blog_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weblogs/edit.html.erb
<h1>Editing weblog</h1>

<%= render 'form' %>

<%= link_to 'Show', @weblog %> |
<%= link_to 'Back', weblogs_path %>

app/views/weblogs/index.html.erb
<h1>ブログ一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Blog name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weblogs.each do |weblog| %>
      <tr>
        <td><%= weblog.profile.name %></td>
        <td><%= weblog.blog_name %></td>
        <% if weblog.user_id == session[:login] %>
          <td><%= link_to '記事を書く', new_entry_path %></td>
        <% end %>
        <td><%= link_to 'Show', weblog %></td>
        <td><%= link_to 'Edit', edit_weblog_path(weblog) %></td>
        <td><%= link_to 'Destroy', weblog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weblog', new_weblog_path %>

app/views/weblogs/new.html.erb
<h1>New weblog</h1>

<%= render 'form' %>

<%= link_to 'Back', weblogs_path %>

app/views/weblogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @weblog.user_id %>
</p>

<p>
  <strong>Blog name:</strong>
  <%= @weblog.blog_name %>
</p>

<%= link_to 'Edit', edit_weblog_path(@weblog) %> |
<%= link_to 'Back', weblogs_path %>